# Site settings
title: StackLeader Blog
email: contact@stackleader.com
description: > # The StackLeader Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stackleader_inc
github_username:  stackleader

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 1
paginate_path: "/pages/page:num/"